export const personalInfo = {
  name: 'Mohanaprasad G',
  title: 'Amazon Connect Developer | AWS Certified | Gen AI | Full Stack',
  email: 'mohanaprasadgmp@gmail.com',
  phone: '+91-9840639433',
  location: 'Chennai, India',
  github: 'https://github.com/mohanaprasad',
  linkedin: 'https://www.linkedin.com/in/mohanaprasad-g-23926a209',
  twitter: '',
  medium: 'https://medium.com/@mohanaprasadgmp',
  bio: [
    "Amazon Connect & Gen AI Developer with 7 years of experience building intelligent, cloud-native contact center solutions — from dynamic Contact Flows and IVR systems to AI-powered voice agents using Amazon Bedrock.",
    "Skilled across the full AWS stack (Lambda, API Gateway, DynamoDB, S3, Contact Lens) with full-stack delivery in Angular and Node.js.",
  ],
  stats: [
    { label: 'Years Experience', value: '7+' },
    { label: 'AWS Certifications', value: '4' },
    { label: 'Projects Delivered', value: '10+' },
    { label: 'Companies Served', value: '3' },
  ],
  interests: [
    'Amazon Connect', 'Gen AI', 'Amazon Bedrock', 'Contact Center AI',
    'Cloud Architecture', 'IVR Systems', 'Conversational AI', 'Full Stack Dev',
  ],
  roles: [
    'Amazon Connect Developer',
    'Gen AI Developer',
    'AWS Certified Developer',
    'Full Stack Developer',
    'Contact Center Specialist',
  ],
};

export const skills = {
  'Amazon Connect': [
    { name: 'Amazon Connect', icon: 'TbBrandAws', color: '#FF9900' },
    { name: 'Contact Flows', icon: 'TbCloudDataConnection', color: '#FF9900' },
    { name: 'Streams API / CCP', icon: 'TbPlugConnected', color: '#FF9900' },
    { name: 'Amazon Lex', icon: 'TbBrandAws', color: '#00B0E7' },
    { name: 'Contact Lens', icon: 'TbActivity', color: '#FF9900' },
  ],
  'AWS Services': [
    { name: 'Lambda', icon: 'TbLambda', color: '#FF9900' },
    { name: 'API Gateway', icon: 'TbApiApp', color: '#FF9900' },
    { name: 'DynamoDB / RDS', icon: 'TbDatabase', color: '#4169E1' },
    { name: 'S3 / CloudFront', icon: 'TbServer', color: '#569A31' },
    { name: 'CloudWatch', icon: 'TbCloud', color: '#FF9900' },
    { name: 'EC2 / ECS', icon: 'TbCloudComputing', color: '#FF9900' },
    { name: 'Amazon Bedrock', icon: 'TbServerSpark', color: '#1A9C3E' },
    { name: 'BedrockAgentCore', icon: 'TbServerSpark', color: '#1A9C3E' },
    { name: 'IAM', icon: 'TbShieldLock', color: '#FF9900' },
  ],
  Development: [
    { name: 'Angular', icon: 'SiAngular', color: '#DD0031' },
    { name: 'Node.js', icon: 'SiNodedotjs', color: '#339933' },
    { name: 'PostgreSQL', icon: 'SiPostgresql', color: '#4169E1' },
    { name: 'MySQL', icon: 'SiMysql', color: '#4479A1' },
  ],
  'AI Tools': [
    { name: 'Claude Code', icon: 'TbBrain', color: '#CC785C' },
    { name: 'OpenAI', icon: 'SiOpenai', color: '#74AA9C' },
  ],
  Hosting: [
    { name: 'GitHub', icon: 'SiGithub', color: '#ffffff' },
    { name: 'Vercel', icon: 'SiVercel', color: '#ffffff' },
  ],
};

export const projects = [
  {
    id: 1,
    title: 'Banking AI Agent',
    description: "Intelligent voice agent leveraging advanced NLU to manage customer banking interactions autonomously. Powered by Amazon Connect and AWS Bedrock, it orchestrates dynamic workflows for hyper-personalized lead generation and contextual cross-sell opportunities.",
    tags: ['Amazon Connect', 'AWS Bedrock', 'Amazon Lex', 'Contact Flows', 'CCP'],
    github: '',
    demo: '',
    featured: true,
    gradient: 'from-orange-500 to-amber-600',
    period: '07/2025 – 11/2025',
    company: 'Hexaware Technologies',
  },
  {
    id: 2,
    title: 'OCS – Singapore Ministry of Education',
    description: "Customized Amazon Connect platform using Contact Flows, Streams API, and Lambda Integrations for intelligent call handling. Implemented real-time transcription, wrap-up automation, and AI-driven enhancements. Built scalable Angular admin modules for seamless contact center operations.",
    tags: ['Amazon Connect', 'Angular', 'Node.js', 'AWS Bedrock', 'PostgreSQL'],
    github: '',
    demo: '',
    featured: true,
    gradient: 'from-violet-500 to-purple-600',
    period: '12/2023 – 04/2025',
    company: 'Servion Global Solutions',
  },
  {
    id: 3,
    title: 'Contact Center Analytics Tool',
    description: "Datalent — a tool to streamline generation, distribution, and analysis of Genesys and Amazon Connect contact center reports. Provides agents with customizable dashboards for real-time insights, with modules for Datasource, Report Builder, and Analysis.",
    tags: ['Angular', 'Node.js', 'MySQL', 'Lambda', 'Amazon Connect'],
    github: '',
    demo: '',
    featured: false,
    gradient: 'from-cyan-500 to-blue-600',
    period: '12/2022 – 10/2023',
    company: 'Servion Global Solutions',
  },
  {
    id: 4,
    title: 'Admin Application – Farmers Insurance',
    description: "Enterprise admin portal for tracking customer data across multiple use cases, each with full CRUD, filtering, sorting, export/import, and login/data audit screens. Built role-based access control with user–group–role mapping, screen-lock to prevent concurrent edits, and auto sign-out after 45 minutes of inactivity.",
    tags: ['Angular', '.NET Core API', 'MySQL', 'RBAC', 'REST API'],
    github: '',
    demo: '',
    featured: false,
    gradient: 'from-blue-500 to-indigo-600',
    period: '11/2022 – 12/2022',
    company: 'Servion Global Solutions',
  },
  {
    id: 5,
    title: 'Dynamic Interaction Routing',
    description: "Centralized configuration platform for Amazon Connect contact flow messages — Broadcast, Greeting, Holiday, TFN, and Survey. Messages are stored dynamically so updates reflect in contact flows immediately, allowing different project teams to reuse the same flow with project-specific content.",
    tags: ['Amazon Connect', 'Node.js', 'Lambda', 'DynamoDB', 'React'],
    github: '',
    demo: '',
    featured: false,
    gradient: 'from-orange-500 to-yellow-500',
    period: '07/2019 – 11/2022',
    company: 'Cognizant Technology Solutions',
  },
  {
    id: 6,
    title: 'OneX Framework',
    description: "Reusable AWS framework that replaces static contact flow prompts with dynamically fetched messages from DynamoDB via API Gateway and Lambda. Designed to redact sensitive data from contact flows and built using Apicurio for API design, with Step Functions orchestrating complex multi-step workflows.",
    tags: ['Amazon Connect', 'Lambda', 'DynamoDB', 'API Gateway', 'Step Functions'],
    github: '',
    demo: '',
    featured: false,
    gradient: 'from-teal-500 to-green-600',
    period: '07/2019 – 11/2022',
    company: 'Cognizant Technology Solutions',
  },
  {
    id: 7,
    title: 'Survey Dashboard',
    description: "Post-call survey system integrated with Dynamic Interaction Routing — when enabled, survey questions are automatically prompted to customers after agent hang-up. Added sentiment analysis via AWS Comprehend with results stored in Elasticsearch, and graphical dashboards for active, past, and abandoned surveys.",
    tags: ['Amazon Connect', 'Lambda', 'AWS Comprehend', 'Elasticsearch', 'DynamoDB'],
    github: '',
    demo: '',
    featured: false,
    gradient: 'from-purple-500 to-pink-600',
    period: '07/2019 – 11/2022',
    company: 'Cognizant Technology Solutions',
  },
  {
    id: 8,
    title: 'CII Banking – IVR Platform',
    description: "End-to-end banking IVR solution combining OneX Framework, Dynamic Interaction Routing, and Survey Dashboard for a unified contact center. Implemented a Lex v2 session-persistence Lambda to resume bot conversations from the last slot rather than restarting, and added VoiceID-based customer authentication directly within the contact flow.",
    tags: ['Amazon Connect', 'Amazon Lex v2', 'VoiceID', 'Lambda', 'API Gateway'],
    github: '',
    demo: '',
    featured: false,
    gradient: 'from-amber-500 to-orange-600',
    period: '07/2019 – 11/2022',
    company: 'Cognizant Technology Solutions',
  },
];

export const experience = [
  {
    id: 1,
    role: 'System Analyst',
    company: 'Hexaware Technologies',
    location: 'Chennai, India',
    period: '06/2025 — Present',
    description: [
      'Leading Amazon Connect implementations with AI-powered automation using Amazon Bedrock and BedrockAgentCore.',
      'Architecting intelligent voice agents with NLU capabilities for autonomous banking customer interactions.',
      'Building custom Agent Workspaces with CCP integration, custom profile, case, and summary sections using Connect APIs.',
    ],
    tags: ['Amazon Connect', 'AWS Bedrock', 'BedrockAgentCore', 'Amazon Lex', 'CCP'],
  },
  {
    id: 2,
    role: 'Senior Software Engineer',
    company: 'Servion Global Solutions',
    location: 'Chennai, India',
    period: '11/2022 — 06/2025',
    description: [
      'Developed and customized Amazon Connect using Contact Flows, Streams API, and Lambda Integrations to enable intelligent call handling and agent experiences.',
      'Implemented real-time transcription, wrap-up automation, and AI-driven enhancements using Amazon Bedrock and Connect AI Assistant.',
      'Built scalable backend services (Node.js/Lambda) and Angular-based admin modules for the Singapore Ministry of Education contact center platform.',
    ],
    tags: ['Amazon Connect', 'Angular', 'Node.js', 'AWS Bedrock', 'PostgreSQL', 'Lambda'],
  },
  {
    id: 3,
    role: 'Associate',
    company: 'Cognizant Technology Solutions',
    location: 'Chennai, India',
    period: '07/2019 — 11/2022',
    description: [
      'Worked on AWS cloud services including Lambda, S3, RDS, IAM, and CloudWatch for enterprise-grade solutions.',
      'Developed full-stack features using Angular frontend and Node.js backend services.',
      'Contributed to contact center development and cloud-native application delivery.',
    ],
    tags: ['AWS', 'Angular', 'Node.js', 'Lambda', 'S3', 'RDS'],
  },
];

export const certifications = [
  {
    id: 1,
    title: 'AWS Certified Developer Associate',
    issuer: 'Amazon Web Services',
    code: 'DVA-C07',
    gradient: 'linear-gradient(135deg, #FF9900, #f59e0b)',
    badgeColor: '#FF9900',
  },
  {
    id: 2,
    title: 'Amazon Connect AI Fundamentals',
    issuer: 'Amazon Web Services',
    code: 'Certification',
    gradient: 'linear-gradient(135deg, #3b82f6, #06b6d4)',
    badgeColor: '#3b82f6',
  },
  {
    id: 3,
    title: 'Amazon Connect Communications Specialist',
    issuer: 'Amazon Web Services',
    code: 'Certification',
    gradient: 'linear-gradient(135deg, #8b5cf6, #7c3aed)',
    badgeColor: '#8b5cf6',
  },
  {
    id: 4,
    title: 'Amazon Connect Developer',
    issuer: 'Amazon Web Services',
    code: 'Certification',
    gradient: 'linear-gradient(135deg, #10b981, #059669)',
    badgeColor: '#10b981',
  },
];

export const blogPosts = [
  {
    id: 1,
    title: 'Building Intelligent Voice Agents with Amazon Connect & Bedrock',
    excerpt: 'A deep dive into architecting AI-powered voice agents that autonomously handle banking customer interactions using Amazon Connect Contact Flows and AWS Bedrock for real-time NLU.',
    date: 'January 15, 2026',
    readTime: '7 min read',
    tags: ['Amazon Connect', 'AWS Bedrock', 'Gen AI'],
    url: 'https://medium.com/@mohanaprasadgmp',
  },
  {
    id: 2,
    title: 'Amazon Connect Streams API: Building Custom Agent Workspaces',
    excerpt: 'How to use the Streams API and CCP to build fully customized agent experiences — from embedding the softphone to integrating case management and AI-generated summaries.',
    date: 'December 10, 2025',
    readTime: '6 min read',
    tags: ['Amazon Connect', 'Streams API', 'CCP'],
    url: 'https://medium.com/@mohanaprasadgmp',
  },
  {
    id: 3,
    title: 'Contact Lens Analytics: Driving Insights from Contact Center Data',
    excerpt: 'Practical guide to using Amazon Connect Contact Lens for conversation analytics, sentiment analysis, and compliance monitoring to drive operational improvements in contact centers.',
    date: 'November 5, 2025',
    readTime: '5 min read',
    tags: ['Contact Lens', 'Analytics', 'Amazon Connect'],
    url: 'https://medium.com/@mohanaprasadgmp',
  },
];
